<a href="https://colab.research.google.com/github/kumar-shivang/Deep-Learning-Tutorials/blob/main/Tensorflow1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import tensorflow as tf

## Creating a Tensor

In [16]:
tensor_zero_dim = tf.constant(4)
print(tensor_zero_dim)

tf.Tensor(4, shape=(), dtype=int32)


In [17]:
tensor_one_dim = tf.constant([1,2,3])
print(tensor_one_dim)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [18]:
tensor_two_dim = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor_two_dim)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [19]:
tensor_three_dim = tf.constant([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
])
print(tensor_three_dim)

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(3, 3, 3), dtype=int32)


In [20]:
tensor_four_dim = tf.constant([
    [
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
    ],
    [
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
]
])
print(tensor_four_dim)

tf.Tensor(
[[[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]


 [[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]], shape=(2, 3, 3, 3), dtype=int32)


### Defining Data Types

In [21]:
tensor_int_16 = tf.constant([1,2,3],dtype=tf.int16)
tensor_float_64 = tf.constant([1,2,3],dtype=tf.float64)
print(tensor_int_16)
print(tensor_float_64)

tf.Tensor([1 2 3], shape=(3,), dtype=int16)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)


### String Tensors

In [22]:
tensor_string_0d = tf.constant("Hello World!")
tensor_string_0d

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World!'>

In [23]:
tensor_string_1d = tf.constant(["Hello","World"])
tensor_string_1d

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'Hello', b'World'], dtype=object)>

### Converting Numpy array to a tensorflow tensor

In [24]:
import numpy as np
np_array = np.array([[1,2,3],[2,3,4]])
print(np_array)

[[1 2 3]
 [2 3 4]]


In [25]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor(
[[1 2 3]
 [2 3 4]], shape=(2, 3), dtype=int64)


### Eye-dentity Matrix

In [26]:
eye_matrix = tf.eye(num_rows=4)
eye_matrix

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [28]:
eye_matrix_asymmetric = tf.eye(num_rows=4,num_columns=5)
eye_matrix_asymmetric

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

#### Multiplying eye matrix

In [29]:
3 * eye_matrix

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[3., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 3.]], dtype=float32)>

In [37]:
eye_matrix_batch = tf.eye(num_rows=2,batch_shape=[2,2])
eye_matrix_batch

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]]],


       [[[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]]]], dtype=float32)>

### Fill Tensor
This creates a tensor filled with a value
```python
tf.fill(shape,value)
```




In [38]:
tensor_fill = tf.fill([3,3],3)
tensor_fill

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]], dtype=int32)>